//created on: Aug 14, 2013
package insurance.pricing

import com.rhc.insurance.Member;
import com.rhc.insurance.Policy;

//dialect "mvel";


rule "highPHlowBH rule"

    when
        //conditions
		$member : Member
        (
        	smokesRegularly == false,
        	filesMedicationRegularly == false
		)
		
		$policy : Policy
		(
			price == 0
		)
        
    then
        //actions
        $policy.price = 500;
        System.out.println("fired rule " + kcontext.getRule().getName());
    

end