//created on: Aug 14, 2013
package insurance.pricing

import insurance.Member;
import insurance.Policy;

dialect "mvel";


rule "A stand alone rule"

    when
        //conditions
        member : Member(smokesRegularly == false && filesMedicationRegularly == true)
		policy : Policy()
        
        
    then
        //actions
        modify(policy) {price=300};
        System.out.println("fired rule " + kcontext.getRule().getName());
    

end

