//created on: Aug 14, 2013
package insurance.pricing

import com.rhc.insurance.Member;
import com.rhc.insurance.Policy;

dialect "mvel";


rule "A stand alone rule"

    when
        //conditions
        member : Member(smokesRegularly == true && filesMedicationRegularly == false)
		policy : Policy()
        
        
    then
        //actions
        modify(policy) {price=1000};
        System.out.println("fired rule " + kcontext.getRule().getName());
    

end

