//created on: Aug 14, 2013
package insurance.pricing

import com.rhc.insurance.Member;
import com.rhc.insurance.Policy;

dialect "mvel";


rule "lowPHhighBH rule"

    when
        //conditions
        $member : Member
        (
        	smokesRegularly == true,
        	filesMedicationRegularly == true
		)
		
		$policy : Policy
		(
			price == 0
		)
        
        
    then
        //actions
        $policy.price = 800;
        System.out.println("fired rule " + kcontext.getRule().getName());
    

end

