//created on: Aug 22, 2012
package com.rhc.brms.ref.rules

//list any import classes here.

import com.rhc.mortgage.domain.Application;


rule "Invalid Application Amount"
	agenda-group "validate-data"

    when
        $application : Application 
        (
        	$amount		:  		amount == null ||
        	amount < 0,
        	valid 	!=	false	 
        )

    then

        System.out.println( "Invalid amount of " + $amount + " for application " + $application );
        
        modify( $application ){
        	setValid( false )
        };

end


rule "No Application ID"
    agenda-group "validate-data"

    when

        $application : Application 
    	(
        	$id	:  	applicationId == null,
        	valid 	!=	false 
    	)

    then
    	
        System.out.println( "Invalid application id of " + $id + " for application " + $application );
		
		modify( $application ){
			setValid( false )
		};
end


rule "No Customer ID"
	agenda-group "validate-data"

    when

        $application 	: 	Application 
    	(
	    	$id	:  	customerId == null,
	    	valid 	!=	false 
    	)

    then
        System.out.println( "Invalid customer ID of " + $id + " for application " + $application );
        
        modify( $application ){
        	setValid( false )
        };

end