//created on: Aug 22, 2012
package com.rhc.brms.ref.rules

//list any import classes here.
import com.rhc.mortgage.domain.StringConcrete;


rule "RHS Test"
	dialect "mvel"
	
	when
		$S : StringConcrete()
	then
		System.out.println( $S.getFoo().concat("this works with java dialect") );
end


rule "RHS Test 2"
	
	when
		$S : StringConcrete()
	then
		System.out.println( $S.getFoo().concat("this works with java dialect") );
end