//created on: Aug 22, 2012
package com.rhc.brms.ref.rules

//list any import classes here.

import com.rhc.brms.ref.domain.Application;
import com.rhc.brms.ref.engine.RulesServiceResponse;


//declare any global variables here
global RulesServiceResponse response;


rule "Invalid Application Amount"
	agenda-group "validate-data"
    when
        $application : Application 
        	(
        	$amount		:  		amount == null 
        				|| 		amount < 0	 
        	)
    then
        System.out.println( "Invalid amount of " + $amount + " for application " + $application );

end


rule "No Application ID"
    agenda-group "validate-data"
    when
        $application 	: 	Application 
        	(
        	$id	:  	applicationId == null 
        	)
    then
        System.out.println( "Invalid credit score of " + $id + " for customer " + $application );

end


rule "No Customer ID"
	agenda-group "validate-data"
    when
        $application 	: 	Application 
        	(
        	$id	:  	customerId == null 
        	)
    then
        System.out.println( "Invalid credit score of " + $id + " for customer " + $application );
        
end
