//created on: Aug 22, 2012
package com.rhc.brms.ref.rules

//list any import classes here.

import com.rhc.brms.ref.domain.Application;
import com.rhc.brms.ref.domain.Customer;
import com.rhc.brms.ref.domain.Mortgage;
import java.math.BigDecimal;


query "Get All Approved Applications"
    
    $application : Application( approved == true )

end

query "Get All Denied Applications"
    
    $application : Application( approved == false )

end
