//created on: Aug 22, 2012
package com.rhc.brms.ref.rules

//list any import classes here.

import com.rhc.mortgage.domain.Application;
import com.rhc.mortgage.domain.Customer;
import com.rhc.mortgage.domain.Mortgage;
import java.math.BigDecimal;


query "Get All Approved Applications"
    
    $application : Application( approved == true )

end

query "Get All Denied Applications"
    
    $application : Application( approved == false )

end

query "Get All New Mortgages"

	$mortgage : Mortgage()

end


